version: "3.8"

services: 
    db:
        restart: always
        build: ./postgres
        container_name: arxivapp_postgres
        env_file: 
            - postgres/database.env
        expose:
            - 5432
        volumes:
            - database:/var/lib/postgresql/data/
        networks: 
            - arxivapp_network
    
    web:
        restart: always
        build:
            context: ./code
        container_name: arxivapp_web
        command: sh -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn ArxivAppBackend.wsgi -b 0.0.0.0:8000"
        volumes:
            - ./code/:/code/
            - ./static/:/static/
        expose:
            - 8000
        depends_on: 
            - db
        networks: 
            - arxivapp_network

    frontend:
        container_name: arxivapp_frontend
        build: ./frontend
        volumes:
            - frontend_build:/frontend/build/
        networks: 
            - arxivapp_network
    
    nginx:
        build: ./nginx
        container_name: arxivapp_nginx
        ports:
            - "54321:80"
        volumes:
            - ./static/:/static/
            - ./nginx/configuration/:/etc/nginx/conf.d/
            - frontend_build:/var/www/frontend/
        depends_on: 
            - web
            - frontend
        networks: 
            - arxivapp_network

volumes:
    database:
    frontend_build:

networks: 
    arxivapp_network:
